### PR TITLE
Use SINTEF/ci-cd

### LINKED ISSUE #201: Reenable documentation CI/CD disabled in PR #200

### LINKED ISSUE #203: Update configuration files for MkDocs
See [this workflow](https://github.com/EMMC-ASBL/oteapi-core/actions/runs/3378122676/jobs/5607913752#step:5:16) to understand which configuration options should be updated.

### LINKED ISSUE #205: Use SINTEF/ci-cd callable workflows and pre-commit hooks
The callable workflows and pre-commit hooks delivered by [SINTEF/ci-cd](https://SINTEF.github.io/ci-cd) are essentially based on the ones already existing here, but by relegating updates and more to an external repository should ensure a more up-to-date and less error-prone workflows and pre-commit hooks regarding documentation updates.

### PR DESCRIPTION
**Pull request by CasperWA**
# Description:

Closes #205 

Use [SINTEF/ci-cd](https://SINTEF.github.io/ci-cd) for callable workflows and pre-commit hooks.

This removes the need for having local invoke tasks and we can even remove the `invoke` package dependency.
Furthermore, the .github/utils folder can be removed, as the only contents (two `txt`-files) are taken care of by the callable workflows instead.

**NB**: Inadvertently, this update also fixes the issues fixed by #204, and effectively renders that PR redundant if this should be merged before.

Fixes #201
Fixes #203

Note, **before this PR can be merged**, the branch protection set on `master` must be updated to require the updated status checks (CI runs) instead of the "old" ones (this is the reason why the PR will be stated as missing required status checks now and until this is changed).

## Type of change:

- [ ] Bug fix.
- [x] New feature.
- [ ] Documentation update.

## Checklist for the reviewer:

This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

### CODE REVIEW

**Comment by daniel-sintef** [comment]
Is it possible to get the build-mkdocs to be part of our pre-commit command? We should try to minimize tests that can only be run on the CI to the minimal possible, and it seems to me mkdocs is something that could be tested local

**Comment by CasperWA** [comment]
> Is it possible to get the build-mkdocs to be part of our pre-commit command? We should try to minimize tests that can only be run on the CI to the minimal possible, and it seems to me mkdocs is something that could be tested local

I fully agree. Since it is not an actual "test", but rather simply running the MkDocs build system, you can simply run the build system.
This is the normal way of getting the documentation locally as well, e.g., for reading offline or for checking changes to the documentation is presented as expected.

I.e., install the `docs` extra (`pip install -e .[docs]`) and run `mkdocs build` locally.
If this is made into a pre-commit hook it _requires_ the user to install the `docs` extra, which is not desireable always. _However_, if pre-commit is even invoked, it can be expected that the user installed using the `dev` extra (which includes all the dependencies that come with `docs` as well), soooo, with that in mind one could create the hook _expecting_ the user to have already installed the package. But it's a slippery slope that will be increasingly difficult to debug down the line.

**Comment by CasperWA** [comment]
Note, before this PR can be merged, the branch protection set on `master` must be updated to require the updated status checks (CI runs) instead of the "old" ones (this is the reason why the PR will be stated as missing required status checks now and until this is changed).

**Comment by daniel-sintef** [comment]
I like this PR so much that I think it is worth showing in the demo this Friday. I *love* seeing massive piles of code being abbreviated into something small and seems much clearer.

**Review by daniel-sintef — APPROVED** [review]

**Pull request merged**
